### ISSUE TITLE
Por favor, borra el temario de FSI

### ISSUE THREAD

**Issue by jmucero97** [Kazzpa/PA-EPDs#1]
Está causando daño en el mundo, grasias

**Comment by Kazzpa** [comment]
What is wrong with you people👬?

Edit: Downvotes? Really? Remember, the downvote 🔵button🔵 is NOT a🅰️ disagree button🔲🔲, it🇮🇹🇮🇹 is NOT there for you to punish 👪people👪 for daring to ask 🙏 real hard ❓questions❓, or pointing↖️ out flaws in YOUR logic. Maybe you should 💭think💭💭 twice before downvoting me 👬like👬 🅰️a🅰️ little bitch, there's a🅰️ reason it's 🇮🇹 called📲 comment KARMA!

**Comment by jmucero97** [comment]
Me parece perfecto
